### ISSUE TITLE
[Desktop] rewards_service_browsertest.cc fails to compile on 1.11.x branch.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#10596]
<pre>
../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:706:10: error: use of undeclared identifier 'creds_tokens_sku_'; did you mean 'brave_test_resp::creds_tokens_sku_'?
         &creds_tokens_sku_));
          ^~~~~~~~~~~~~~~~~
          brave_test_resp::creds_tokens_sku_
</pre>

**Comment by NejcZdovc** [comment]
fixed in https://github.com/brave/brave-core/pull/6026
