### ISSUE TITLE
Fix a build on master related to 1.39.x version

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/brave-browser#22300]
master is broken currently on Android with such an error:
```
../../brave/android/java/org/chromium/chrome/browser/ntp/BraveNewTabPageLayout.java:748: error: cannot find symbol
                    mParentScrollView.fullScroll(ScrollView.FOCUS_UP);
                                                 ^
  symbol:   variable ScrollView
  location: class BraveNewTabPageLayout
1 error
```
