### ISSUE TITLE
[cr117 follow up] Fix build on Win arm64.

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#32812]
Build fails with:

<pre>
../../brave/chromium_src/chrome/browser/component_updater/widevine_cdm_component_installer.cc(176,29): error: use of undeclared identifier 'GetPlatformDirectory'
   176 |   if (base::DirectoryExists(GetPlatformDirectory(install_dir))) {
       |                             ^        
 ../../brave/chromium_src/chrome/browser/component_updater/widevine_cdm_component_installer.cc(255,36): error: use of undeclared identifier 'GetPlatformDirectory'
   255 |   base::FilePath arm64_directory = GetPlatformDirectory(install_dir_);
       |                                    ^
</pre>

**QA Test Plan**:
Please, verify that Widevine works on Windows ARM64 build.

**Comment by mihaiplesa** [comment]
This needs uplift.

**Comment by mkarolin** [comment]
@mihaiplesa uplift to 1.59.x is here https://github.com/brave/brave-core/pull/20038.
Doesn't need to be uplifted to 1.58.x (the fix is for code introduced in https://github.com/brave/brave-core/pull/18695 which is only up to 1.59.x).

**Comment by kjozwiak** [comment]
The above requires `1.59.79` or higher for `1.59.x` verification 👍

**Comment by MadhaviSeelam** [comment]
Verification `PASSED` using 
```
Brave | 1.59.90 Chromium: 117.0.5938.88 (Official Build) beta (arm64)
-- | --
Revision | 5272112c86588e44ec7c0b766c318cddccbced85
OS | Windows 11 Version 22H2 (Build 22621.2283)
```

Verification of this issue is done on `1.59.86` via https://github.com/brave/brave-browser/issues/28318#issuecomment-1720273018
