### ISSUE TITLE
Broken sync desktop tests

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/brave-browser#28796]
```
[2023-02-28T01:29:19.043Z] ../../brave/components/sync/driver/brave_sync_service_impl_unittest.cc:426:57: error: no viable conversion from 'OnceCallback<internal::MakeUnboundRunType<(lambda at ../../brave/components/sync/driver/brave_sync_service_impl_unittest.cc:427:7), bool *>>' to 'OnceCallback<void (bool)>'
```
Regression after https://github.com/brave/brave-core/pull/17369
