### ISSUE TITLE
Browser tests fail to build on Windows

### ISSUE THREAD

**Issue by mkarolin** [brave/brave-browser#9661]
<pre>
../../brave/browser/speedreader/speedreader_browsertest.cc(45,51): error: no matching member function for call to 'Append'
    base::FilePath whitelist_path = test_data_dir.Append(kTestWhitelist);
                                    ~~~~~~~~~~~~~~^~~~~~
../..\base/files/file_path.h(326,12): note: candidate function not viable: no known conversion from 'const char [27]' to 'base::FilePath::StringPieceType' (aka 'BasicStringPiece<basic_string<wchar_t, char_traits<wchar_t>, allocator<wchar_t> > >') for 1st argument
  FilePath Append(StringPieceType component) const WARN_UNUSED_RESULT;
           ^
../..\base/files/file_path.h(327,12): note: candidate function not viable: no known conversion from 'const char [27]' to 'const base::FilePath' for 1st argument
  FilePath Append(const FilePath& component) const WARN_UNUSED_RESULT;
           ^
1 error generated.
</pre>

**Comment by bsclifton** [comment]
Possibly caused by https://github.com/brave/brave-core/pull/5142
