### ISSUE TITLE
New tab page shows white screen

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-browser#52836]
### Description

Some users reported that NTP suddenly became a white screen after updating to 1.87.186. Both Windows users and Mac users reported the same issue.

https://community.brave.app/t/topic/649309

```
brave_new_tab_page.bundle.js:2 Error: Mismatched closing tag: /$1 in message "今月表示した広告数: $10件/$1"
    at o (brave_new_tab_page.bundle.js:2:277620)
    at jl (brave_new_tab_page.bundle.js:1617:3267)
    at El (brave_new_tab_page.bundle.js:2:179705)
    at Ki (brave_new_tab_page.bundle.js:2:191286)
    at _s (brave_new_tab_page.bundle.js:2:237013)
    at Sc (brave_new_tab_page.bundle.js:2:225398)
    at hc (brave_new_tab_page.bundle.js:2:225326)
    at gc (brave_new_tab_page.bundle.js:2:225189)
    at ac (brave_new_tab_page.bundle.js:2:222024)
    at oc (brave_new_tab_page.bundle.js:2:220580)
```

### Steps to reproduce

1. Connect bitFlyer account from the new tab page wedget
2. Show a new tab page

<img width="1198" height="790" alt="Image" src="https://github.com/user-attachments/assets/2f39c5aa-247f-424e-908a-029ce012cde3" />

### Actual result

It doesn't show background image and any other components. It becomes a white screen. And after reloading NTP, it shows the usual NTP components for a moment, then it becomes white again.

**`Example`** | **`Example`** | **`Example`**
---------------|-----------------|-----------------
<img width="1380" height="750" alt="Image" src="https://github.com/user-attachments/assets/693d53f0-9055-4a79-b97d-868a900a2e5d" /> | <img width="1920" height="1045" alt="Image" src="https://github.com/user-attachments/assets/e7844ba8-012c-4e8f-9556-a3649bceb070" /> | <img width="1866" height="1386" alt="Image" src="https://github.com/user-attachments/assets/63e417a2-1689-45de-9e9e-75bb48c54cd9" />

### Expected result

A background image and other components should be shown on a new tab page.

### Reproduces how often

Intermittent issue

### Brave version (brave://version info)

1.87.186

### Channel information

- [x] release (stable)
- [ ] beta
- [ ] nightly

### Reproducibility

- [x] with Brave Shields disabled
- [x] with Brave Rewards disabled
- [ ] in the latest version of Chrome
