### ISSUE TITLE
Build failure with https://github.com/brave/brave-core/pull/34806

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-browser#53786]
```
gen/chrome/browser/resources/settings/preprocessed/default_brave_shields_page/components/brave_adblock_scriptlet_editor.ts:72:23 - error TS2551: Property 'oldScriptletName_' does not exist on type 'AdblockScriptletEditor'. Did you mean 'scriptletName_'?

72       let name = this.oldScriptletName_
                         ~~~~~~~~~~~~~~~~~

  gen/chrome/browser/resources/settings/preprocessed/default_brave_shields_page/components/brave_adblock_scriptlet_editor.ts:55:11
    55   declare scriptletName_: string
                 ~~~~~~~~~~~~~~
    'scriptletName_' is declared here.


Found 1 error in gen/chrome/browser/resources/settings/preprocessed/default_brave_shields_page/components/brave_adblock_scriptlet_editor.ts:72
```
