### ISSUE TITLE
Lint errors after merging SKUS pull request

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#20542]
## Description
Caused by https://github.com/brave/brave-core/pull/10847

There are some references used in the interop between C++ and Rust which our linter (`npm run lint`) is saying we should either make `const` or use a pointer.

## The lint errors
```
08:40:36  components/skus/browser/rs/cxx/src/shim.h:97:  Is this a non-const reference? If so, make const or use a pointer: skus::SkusContext& ctx  [runtime/references] [2]
08:40:36  components/skus/browser/rs/cxx/src/shim.h:98:  Is this a non-const reference? If so, make const or use a pointer: skus::SkusContext& ctx  [runtime/references] [2]
08:40:36  components/skus/browser/rs/cxx/src/shim.h:101:  Is this a non-const reference? If so, make const or use a pointer: skus::SkusContext& ctx  [runtime/references] [2]
```

```
08:40:36  components/skus/browser/skus_context_impl.cc:76:  Is this a non-const reference? If so, make const or use a pointer: skus::SkusContext& ctx  [runtime/references] [2]
08:40:36  components/skus/browser/skus_context_impl.cc:80:  Is this a non-const reference? If so, make const or use a pointer: skus::SkusContext& ctx  [runtime/references] [2]
08:40:36  components/skus/browser/skus_context_impl.cc:87:  Is this a non-const reference? If so, make const or use a pointer: skus::SkusContext& ctx  [runtime/references] [2]
```

**Comment by bsclifton** [comment]
If you try to change the references to `const`, this is what you get:
```
gen/brave/components/skus/browser/rs/cxx/src/lib.rs.cc(1196,10): error: cannot initialize a variable of type 'void (*)(::skus::SkusContext &)' (aka 'void (*)(skus::SkusContext &)') with an lvalue of type 'void (const skus::SkusContext &)': type mismatch at 1st parameter ('::skus::SkusContext &' (aka 'skus::SkusContext &') vs 'const skus::SkusContext &')
  void (*shim_purge$)(::skus::SkusContext &) = ::skus::shim_purge;
         ^                                     ~~~~~~~~~~~~~~~~~~
gen/brave/components/skus/browser/rs/cxx/src/lib.rs.cc(1201,10): error: cannot initialize a variable of type 'void (*)(::skus::SkusContext &, ::rust::Str, ::rust::Str)' (aka 'void (*)(skus::SkusContext &, rust::Str, rust::Str)') with an lvalue of type 'void (const skus::SkusContext &, rust::cxxbridge1::Str, rust::cxxbridge1::Str)': type mismatch at 1st parameter ('::skus::SkusContext &' (aka 'skus::SkusContext &') vs 'const skus::SkusContext &')
  void (*shim_set$)(::skus::SkusContext &, ::rust::Str, ::rust::Str) = ::skus::shim_set;
         ^                                                             ~~~~~~~~~~~~~~~~
gen/brave/components/skus/browser/rs/cxx/src/lib.rs.cc(1206,20): error: cannot initialize a variable of type '::rust::String (*)(::skus::SkusContext &, ::rust::Str)' (aka 'rust::String (*)(skus::SkusContext &, rust::Str)') with an lvalue of type '::rust::String (const skus::SkusContext &, rust::cxxbridge1::Str)': type mismatch at 1st parameter ('::skus::SkusContext &' (aka 'skus::SkusContext &') vs 'const skus::SkusContext &')
  ::rust::String (*shim_get$)(::skus::SkusContext &, ::rust::Str) = ::skus::shim_get;
                   ^                                                ~~~~~~~~~~~~~~~~
3 errors generated.
```
cc: @evq 

This is something we knew about and I didn't fix. I think it has to do with how Rust is expecting C compatible ABI
