### ISSUE TITLE
Transient build error: "fatal error: 'brave/grit/brave_generated_resources.h' file not found"

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#3854]
As reported by @mbacchi this build error can happen:

```
09:19:15 In file included from C:\jenkins\ia32-nightly\src\brave\chromium_src\ui\base\webui\web_ui_util.cc:15:
09:19:15 ../../brave/chromium_src\chrome/grit/generated_resources.h(1,10): fatal error: 'brave/grit/brave_generated_resources.h' file not found
09:19:15 #include "brave/grit/brave_generated_resources.h"
09:19:15          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
09:19:15 1 error generated.
09:19:15 [18822/37867] CXX obj/ui/base/clipboard/clipboard/custom_data_helper.obj
09:19:15
```

Investigation shows that we have modified a file in ui/base to include "chrome/grit/generated_resources.h" but that is rewritten to "brave/grit/brave_generated_resources.h" and there is no dep to the project which generates that.

Setting milestone of 0.63.x since this code was introduced with https://github.com/brave/brave-core/pull/1422

**Comment by bsclifton** [comment]
Moved to 0.64.x milestone for the moment - I tried to do an uplift, but it failed. @petemill is this Chromium 74 specific?

**Comment by petemill** [comment]
@bsclifton That's strange - https://github.com/brave/brave-core/pull/1422 is on 0.63.x and the code is there. Probably an issue uplifting a .patch. I'll resolve it manually.
Thanks
