### ISSUE TITLE
Windows Component build is broken due to https://github.com/brave/brave-core/pull/11468

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#20038]
From @goodov at https://github.com/brave/brave-core/pull/11468#commitcomment-61690391

> this breaks component builds (on Windows at least), because common/brave_features.h is not a part of a gn's component, thus this define shouldn't be used here at all.
> 
> ../../brave/common/brave_features.cc(22,21): error: 'features::kTabAudioIconInteractive' redeclared without 'dllimport' attribute: 'dllexport' attribute added [-Werror,-Winconsistent-dllimport]
> const base::Feature kTabAudioIconInteractive{"TabAudioIconInteractive",
>                     ^
> ../..\brave/common/brave_features.h(21,28): note: previous declaration is here
> extern const base::Feature kTabAudioIconInteractive;
> Chrome's feature file implemented as a component and has a special define IS_CHROME_FEATURES_IMPL to allow the COMPONENT_EXPORT macro to work properly:
> chromium/chromium@829dd33/chrome/common/BUILD.gn#L554-L560

**Comment by kjozwiak** [comment]
Moving this into `1.34.x` as per the discussion we had on Tuesday's b-b meeting. It doesn't seem like we'll get another C96 before we release `1.34.x` with C97. However, if we do end up getting another C96 and it ends up fixing a zero day security issue, we'll re-create a `1.33.x - Release #2` milestone and move this issue back as it's already in the `1.33.x` branch.
