### ISSUE TITLE
[Desktop] Compile error due to NTP app.tsx

### ISSUE THREAD

**Issue by petemill** [brave/brave-browser#12961]
`"Property 'saveShowAddCard' does not exist on type..."`

This was introduced with https://github.com/brave/brave-core/pull/7111 which must have had a bad merge at the last minute 😢
