### ISSUE TITLE
JavaScript unit test failure: `components/test/brave_new_tab_ui/components/settings_test.tsx`

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-browser#24787]
## Description 
Seems to be one error when running `npm run test-unit`

This was masked because of the CI script. More details here (employee only Slack link):
https://bravesoftware.slack.com/archives/C7VLGSR55/p1660741434336999

May have been unintentionally caused by https://github.com/brave/brave-core/pull/14518
```
FAIL components/test/brave_new_tab_ui/components/settings_test.tsx
  ● Test suite failed to run

    Cannot find module '$web-common/locale' from 'components/brave_new_tab_ui/components/default/searchPromotion/searchBox.tsx'

    Require stack:
      components/brave_new_tab_ui/components/default/searchPromotion/searchBox.tsx
      components/brave_new_tab_ui/components/default/searchPromotion/index.tsx
      components/brave_new_tab_ui/components/default/index.ts
      components/test/brave_new_tab_ui/components/settings_test.tsx

      1 | import * as React from 'react'
      2 | import styled from 'styled-components'
    > 3 | import { getLocale } from '$web-common/locale'
        | ^
      4 |
      5 | const Box = styled.div`
      6 |   display: flex;

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (components/brave_new_tab_ui/components/default/searchPromotion/searchBox.tsx:3:1)
```

## Steps to Reproduce

   1. Clone repo (`master` branch)
   2. `npm run test-unit`

**Comment by bsclifton** [comment]
@simonhong can you check this out please? 😄
