### ISSUE TITLE
Master debug build failure - unimplemented pure virtual method 'DumpContextDependencies' in 'BraveActionAPIDependencyManager'

### ISSUE THREAD

**Issue by simonhong** [brave/brave-browser#6628]
```
In file included from ../../brave/browser/extensions/api/brave_action_api.cc:13:
../../base/no_destructor.h:54:20: error: allocating an object of abstract class type '(anonymous namespace)::BraveActionAPIDependencyManager'
    new (storage_) T(std::forward<Args>(args)...);
                   ^
../../brave/browser/extensions/api/brave_action_api.cc:29:64: note: in instantiation of function template specialization 'base::NoDestructor<(anonymous namespace)::BraveActionAPIDependencyManager>::NoDestructor<>' requested here
    static base::NoDestructor<BraveActionAPIDependencyManager> factory;
                                                               ^
../../components/keyed_service/core/dependency_manager.h:103:16: note: unimplemented pure virtual method 'DumpContextDependencies' in 'BraveActionAPIDependencyManager'
  virtual void DumpContextDependencies(void* context) const = 0;
               ^
1 error generated.
```

**Comment by bsclifton** [comment]
I believe this was caused by https://github.com/brave/brave-core/pull/3664
