### ISSUE TITLE
Rewards browser test failed

### ISSUE THREAD

**Issue by yrliou** [brave/brave-browser#3883]
Caused by https://github.com/brave/brave-core/pull/1943 which is in master & dev

```
hidden -c ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc -o obj/brave/test/brave_browser_tests/rewards_service_browsertest.o
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:391:3: error: no member named 'gmock_OnGetDebug' in 'BraveRewardsBrowserTest_HandleFlagsSingleArg_Test'
11:49:54    EXPECT_CALL(*this, OnGetDebug(true));
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1979:3: note: expanded from macro 'EXPECT_CALL'
11:49:54    GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1971:16: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
11:49:54    ((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
11:49:54     ~~~~~~~~~~~ ^
11:49:54  <scratch space>:7:1: note: expanded from here
11:49:54  gmock_OnGetDebug
11:49:54  ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:393:3: error: no member named 'gmock_OnGetDebug' in 'BraveRewardsBrowserTest_HandleFlagsSingleArg_Test'
11:49:54    EXPECT_CALL(*this, OnGetDebug(false)).Times(2);
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1979:3: note: expanded from macro 'EXPECT_CALL'
11:49:54    GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1971:16: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
11:49:54    ((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
11:49:54     ~~~~~~~~~~~ ^
11:49:54  <scratch space>:12:1: note: expanded from here
11:49:54  gmock_OnGetDebug
11:49:54  ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:395:3: error: no member named 'gmock_OnGetDebug' in 'BraveRewardsBrowserTest_HandleFlagsSingleArg_Test'
11:49:54    EXPECT_CALL(*this, OnGetDebug(true)).Times(2);
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1979:3: note: expanded from macro 'EXPECT_CALL'
11:49:54    GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1971:16: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
11:49:54    ((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
11:49:54     ~~~~~~~~~~~ ^
11:49:54  <scratch space>:17:1: note: expanded from here
11:49:54  gmock_OnGetDebug
11:49:54  ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:398:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:404:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:410:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:416:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:422:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:466:3: error: no member named 'gmock_OnGetDebug' in 'BraveRewardsBrowserTest_HandleFlagsMultipleFlags_Test'
11:49:54    EXPECT_CALL(*this, OnGetDebug(false));
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1979:3: note: expanded from macro 'EXPECT_CALL'
11:49:54    GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1971:16: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
11:49:54    ((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
11:49:54     ~~~~~~~~~~~ ^
11:49:54  <scratch space>:69:1: note: expanded from here
11:49:54  gmock_OnGetDebug
11:49:54  ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:481:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:487:3: error: no member named 'gmock_OnGetDebug' in 'BraveRewardsBrowserTest_HandleFlagsWrongInput_Test'
11:49:54    EXPECT_CALL(*this, OnGetDebug(true));
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1979:3: note: expanded from macro 'EXPECT_CALL'
11:49:54    GMOCK_ON_CALL_IMPL_(obj, InternalExpectedAt, call)
11:49:54    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:49:54  ../../third_party/googletest/src/googlemock/include/gmock/gmock-spec-builders.h:1971:16: note: expanded from macro 'GMOCK_ON_CALL_IMPL_'
11:49:54    ((mock_expr).gmock_##call)(::testing::internal::GetWithoutMatchers(), \
11:49:54     ~~~~~~~~~~~ ^
11:49:54  <scratch space>:111:1: note: expanded from here
11:49:54  gmock_OnGetDebug
11:49:54  ^
11:49:54  ../../brave/components/brave_rewards/browser/rewards_service_browsertest.cc:502:3: error: use of undeclared identifier 'GetDebug'
11:49:54    GetDebug();
11:49:54    ^
11:49:54  12 errors generated.
```
